// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApiWithPostgreSQL.DB;

#nullable disable

namespace WebApiWithPostgreSQL.DB.Migrations
{
    [DbContext(typeof(AppDbCtx))]
    [Migration("20250918231141_InitDb")]
    partial class InitDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApiWithPostgreSQL.DB.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Email = "vasiliy@email.com",
                            Name = "Vasiliy"
                        },
                        new
                        {
                            Id = 2L,
                            Email = "vitaliy@email.com",
                            Name = "Vitaliy"
                        },
                        new
                        {
                            Id = 3L,
                            Email = "valeriy@email.com",
                            Name = "Valeriy"
                        },
                        new
                        {
                            Id = 4L,
                            Email = "oleg@email.com",
                            Name = "Oleg"
                        },
                        new
                        {
                            Id = 5L,
                            Email = "ekaterina@email.com",
                            Name = "Ekaterina"
                        },
                        new
                        {
                            Id = 6L,
                            Email = "maya@email.com",
                            Name = "Maya"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
